#include <zephyr/zephyr.h>
#include <zephyr/drivers/gpio.h>

// TODO this probably deservers a litex,control compatible on DTS
// (or properly import the header generated by litex)
#define CTRL_RESET 0xf0000000L

#define N_LEDS DT_PROP(DT_NODELABEL(user_leds), ngpios)

const struct device *leds;
const struct device *push_btns;
const struct device *user_sw;
static uint32_t led_counter;

static struct gpio_callback push_btn_gpio_cb;
static struct gpio_callback user_sw_gpio_cb;

static void led_timer_handler(struct k_timer *timer)
{
	ARG_UNUSED(timer);

	int i;
	for (i = 0; i < N_LEDS; i++)
		gpio_pin_set(leds, i, (led_counter & (1 << i)));

	led_counter = (led_counter + 1) % (1 << N_LEDS);
}

K_TIMER_DEFINE(led_timer, led_timer_handler, NULL);

void push_btn_cb(const struct device *dev, struct gpio_callback *cb,
		 uint32_t pin)
{
	// TODO: check a way to reboot to the bootloader on the press of
	// some button.
	printk("Button pressed, pin: %u, device: %p\n", pin, dev);
	if (pin == 8)
		*((uint32_t *)CTRL_RESET) = 1;
}

void user_sw_cb(const struct device *dev, struct gpio_callback *cb,
		uint32_t pin)
{
	printk("Switch moved, pin: %u, device: %p\n", pin, dev);
}

void main(void)
{
	int ret, i;

	printk("main started!\n");

	leds = device_get_binding("user_leds");
	push_btns = device_get_binding("push_btns");
	user_sw = device_get_binding("user_sw");
	printk("Got leds dev: %p push btns dev: %p user switches %p\n",
	       leds, push_btns, user_sw);

	// TODO get those from device tree
	for (i = 0; i < 18; i++) {
		ret = gpio_pin_configure(user_sw, i, GPIO_INPUT);
		ret =  gpio_pin_interrupt_configure(user_sw, i,
						    GPIO_INT_EDGE_BOTH);
	}
	gpio_init_callback(&user_sw_gpio_cb, user_sw_cb, BIT(18) - 1);
	ret = gpio_add_callback(user_sw, &user_sw_gpio_cb);

	for (i = 0; i < 4; i++) {
		ret = gpio_pin_configure(push_btns, i, GPIO_INPUT);
		ret =  gpio_pin_interrupt_configure(push_btns, i,
						    GPIO_INT_EDGE_BOTH);
	}
	gpio_init_callback(&push_btn_gpio_cb, push_btn_cb, 0xf);
	ret = gpio_add_callback(push_btns, &push_btn_gpio_cb);

	k_timer_start(&led_timer, K_MSEC(2000), K_MSEC(2000));
}
